#! /bin/bash
. ~/.lpassfunctions 

LASTPASS_KEY_FOLDER="dharris@gmail.com/API_KEYS"
set_env_var_from_lastpass AWS_SECRET_ACCESS_KEY
set_env_var_from_lastpass AWS_ACCESS_KEY_ID

if [[ $# -lt 1 ]]
then
    WHAT="code"
else
    WHAT=$1
fi

if [[ $WHAT == "code" ]]
then
    pandoc -s --template=static/page-template.html -f markdown -t html < about.md  > about.html
    aws s3 sync . s3://wilsonschedule.com --exclude ".git/*" --exclude "students/*" \
        --exclude="todo.org" --exclude="aws-sync"
elif [[ $WHAT == "data" ]]
then
    aws s3 sync students/ s3://data.wilsonschedule.com
fi


